import type React from 'react';


export type SvgProps = React.ComponentProps<'svg'> & {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  mode?: 'light' | 'dark';
};

export const sizeMap: Record<'xs' | 'sm' | 'md' | 'lg' | 'xl', number> = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
};

export const iconNames = [
  'abstract-exception',
  'add-any',
  'alias',
  'annotation',
  'annotation-folder',
  'class',
  'class-abstract',
  'class-anonymous',
  'class-initializer',
  'config',
  'constant',
  'controller',
  'copy-of-folder',
  'data-column',
  'data-tables',
  'desktop',
  'edit-folder',
  'enum',
  'error-introduction',
  'exception',
  'exclude-root',
  'excluded-generated',
  'favorites',
  'field',
  'folder',
  'function',
  'generated',
  'generated-source',
  'generated-test-root',
  'gvariable',
  'home-folder',
  'idea-project',
  'include',
  'interface',
  'jdk',
  'lambda',
  'library',
  'library-folder',
  'local-scope',
  'method',
  'method-abstract',
  'method-reference',
  'model-class',
  'module',
  'module-group',
  'module-java',
  'module8x8',
  'new-folder',
  'package',
  'parameter',
  'plugin',
  'pp-web',
  'property',
  'record',
  'resource-bundle',
  'resources-root',
  'server',
  'servlet',
  'shared-scope',
  'source-root',
  'star',
  'star-empty',
  'static',
  'template',
  'test',
  'test-group',
  'test-ignored',
  'test-resources-root',
  'test-root',
  'test-source-folder',
  'text-area',
  'type',
  'unloaded-module',
  'up-folder',
  'variable',
  'warning-introduction',
  'web-resources',
] as const;

export type IconName = (typeof iconNames)[number];
