// Generate registry/icons/manifest.ts from each domain's barrel (index.ts).
//
// The manifest is the single name -> component map used by <SVG name />.
// It resolves through the per-domain barrel (import('./<domain>')) so that
// a page rendering many icons from one domain loads a single chunk.
//
// Reusable: invoked on demand in Phase 0, and by generate-icons.mts after
// any regeneration in Phase 1.
//
// Usage: pnpm tsx scripts/generate-manifest.mts

import { promises as fs } from 'fs';
import path from 'path';

const ICONS_ROOT = path.join(process.cwd(), 'registry', 'icons');
const OUTPUT_PATH = path.join(ICONS_ROOT, 'manifest.ts');

interface Entry {
  /** lowercase pathname, e.g. "database/redis" or "general/ai-asisstant/ai-assistant" */
  pathname: string;
  /** actual on-disk domain dir (preserved casing for case-sensitive filesystems), e.g. "Database" */
  domain: string;
  /** PascalCase named export from the domain barrel, e.g. "Redis" */
  component: string;
}

// Matches: export { Redis } from './redis';
//      and: export { AiAssistant } from './ai-asisstant/ai-assistant';
const EXPORT_RE =
  /^\s*export\s+\{\s*([A-Z][A-Za-z0-9_]*)\s*\}\s+from\s+['"]\.\/([^'"]+)['"]\s*;?\s*$/;

// Matches: export * from './expui'  (wildcard re-export of a subcategory barrel)
const WILDCARD_RE = /^\s*export\s+\*\s+from\s+['"]\.\/([^'"]+)['"]\s*;?\s*$/;

async function dirHasBarrel(d: string): Promise<boolean> {
  try {
    await fs.stat(path.join(d, 'index.ts'));
    return true;
  } catch {
    return false;
  }
}

async function collectEntries(): Promise<Entry[]> {
  const entries: Entry[] = [];
  const children = await fs.readdir(ICONS_ROOT, { withFileTypes: true });

  for (const child of children) {
    if (!child.isDirectory()) continue;
    const domainOnDisk = child.name;
    const domainDir = path.join(ICONS_ROOT, domainOnDisk);

    if (!(await dirHasBarrel(domainDir))) continue;

    const barrelSrc = await fs.readFile(
      path.join(domainDir, 'index.ts'),
      'utf8',
    );

    for (const line of barrelSrc.split('\n')) {
      const match = EXPORT_RE.exec(line);
      if (!match) continue;
      const [, component, relPath] = match;
      const pathname = `${domainOnDisk}/${relPath}`.toLowerCase();
      entries.push({ pathname, domain: domainOnDisk, component });
    }

    // Follow `export * from './<sub>'` — resolve the subcategory barrel so
    // namespaced packs (e.g. database/expui/<icon>) are reachable via the
    // root domain barrel (loader still imports the root, so chunking holds).
    for (const line of barrelSrc.split('\n')) {
      const wc = WILDCARD_RE.exec(line);
      if (!wc) continue;
      const sub = wc[1];
      let subSrc: string;
      try {
        subSrc = await fs.readFile(
          path.join(domainDir, sub, 'index.ts'),
          'utf8',
        );
      } catch {
        continue;
      }
      for (const subLine of subSrc.split('\n')) {
        const sm = EXPORT_RE.exec(subLine);
        if (!sm) continue;
        const [, component, relPath] = sm;
        entries.push({
          pathname: `${domainOnDisk}/${sub}/${relPath}`.toLowerCase(),
          domain: domainOnDisk,
          component,
        });
      }
    }
  }

  return entries;
}

function buildSlugIndex(entries: Entry[]): Map<string, string[]> {
  const index = new Map<string, string[]>();
  for (const entry of entries) {
    const slug = entry.pathname.slice(entry.pathname.lastIndexOf('/') + 1);
    const list = index.get(slug) ?? [];
    list.push(entry.pathname);
    index.set(slug, list);
  }
  return index;
}

function escapeKey(key: string): string {
  // quote keys that contain '/' or '-' (not valid bare identifiers)
  return /[/-]/.test(key) ? `'${key}'` : key;
}

async function main() {
  const entries = await collectEntries();
  entries.sort((a, b) => a.pathname.localeCompare(b.pathname));

  if (entries.length === 0) {
    throw new Error(
      'No icon entries found. Ensure registry/icons/<domain>/index.ts barrels exist.',
    );
  }

  const slugIndex = buildSlugIndex(entries);
  const ambiguous = [...slugIndex.entries()].filter(([, v]) => v.length > 1);

  // Group entries by domain for readability.
  const byDomain = new Map<string, Entry[]>();
  for (const entry of entries) {
    const list = byDomain.get(entry.domain) ?? [];
    list.push(entry);
    byDomain.set(entry.domain, list);
  }

  const lines: string[] = [];
  lines.push(
    '// Auto-generated by scripts/generate-manifest.mts — DO NOT EDIT',
  );
  lines.push(
    '// Maps every icon pathname to a lazy loader over its domain barrel.',
  );
  lines.push(
    '// Resolution: pathname -> iconRegistry[name]; bare slug -> slugIndex[name].',
  );
  lines.push('');
  lines.push('export const iconRegistry = {');

  const sortedDomains = [...byDomain.keys()].sort((a, b) => a.localeCompare(b));
  sortedDomains.forEach((domain, domainIdx) => {
    const list = byDomain.get(domain)!;
    if (domainIdx > 0) lines.push('');
    lines.push(`  // ${domain} (${list.length})`);
    for (const entry of list) {
      lines.push(
        `  ${escapeKey(entry.pathname)}: () => import('./${entry.domain}').then(` +
          `(m) => ({ default: m.${entry.component} })),`,
      );
    }
  });
  lines.push('} as const;');
  lines.push('');
  lines.push('export type IconPathname = keyof typeof iconRegistry;');
  lines.push('');
  lines.push('export const slugIndex: Record<string, IconPathname[]> = {');
  for (const [slug, pathnames] of [...slugIndex.entries()].sort((a, b) =>
    a[0].localeCompare(b[0]),
  )) {
    const pathnamesLiteral = `[${pathnames.map((p) => `'${p}'`).join(', ')}]`;
    lines.push(`  ${escapeKey(slug)}: ${pathnamesLiteral},`);
  }
  lines.push('};');
  lines.push('');

  await fs.writeFile(OUTPUT_PATH, lines.join('\n'));

  const ambiguousList = ambiguous
    .map(([slug, paths]) => `${slug} (${paths.length})`)
    .join(', ');

  console.log(
    `manifest.ts: ${entries.length} icons across ${sortedDomains.length} domains. ` +
      `Wrote ${OUTPUT_PATH}.` +
      (ambiguous.length
        ? `\nAmbiguous bare slugs (${ambiguous.length}): ${ambiguousList}`
        : '\nNo ambiguous bare slugs.'),
  );
}

void main().catch((err) => {
  console.error(err);
  process.exit(1);
});
