import { promises as fs } from 'fs';
import path from 'path';

const ICONS_ROOT_PATH = path.join(process.cwd(), 'registry', 'icons');
const ICONS_REGISTRY_PATH = path.join(
  process.cwd(),
  'registry',
  'components',
  'svg',
  'registry.ts',
);

type IconComponentEntry = {
  iconPath: string;
  exportName: string;
};

function getIconExportName(source: string, iconPath: string) {
  if (source.includes('export default')) {
    return 'default';
  }

  const match = source.match(/export\s+(?:const|function)\s+([^\s(<:=]+)/u);

  if (match) {
    return match[1];
  }

  throw new Error(`Unable to resolve icon export for ${iconPath}`);
}

async function collectIconComponentEntries(
  dir: string,
): Promise<IconComponentEntry[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const iconEntries: IconComponentEntry[] = [];

  if (entries.some((entry) => entry.isFile() && entry.name === 'index.tsx')) {
    const iconPath = path
      .relative(ICONS_ROOT_PATH, dir)
      .split(path.sep)
      .join('/');
    const source = await fs.readFile(path.join(dir, 'index.tsx'), 'utf-8');

    iconEntries.push({
      iconPath,
      exportName: getIconExportName(source, iconPath),
    });
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) {
      continue;
    }

    iconEntries.push(
      ...(await collectIconComponentEntries(path.join(dir, entry.name))),
    );
  }

  return iconEntries;
}

function buildIconLoaderSource(importPath: string, exportName: string) {
  if (exportName === 'default') {
    return `() => import(${JSON.stringify(importPath)})`;
  }

  return `() => import(${JSON.stringify(importPath)}).then((mod) => ({ default: mod.${exportName} }))`;
}

function buildIconsRegistrySource(iconEntries: IconComponentEntry[]) {
  const basenameCount = new Map<string, number>();
  const registryEntries = new Map<
    string,
    { importPath: string; exportName: string }
  >();

  for (const { iconPath } of iconEntries) {
    const basename = iconPath.split('/').at(-1);

    if (!basename) {
      continue;
    }

    basenameCount.set(basename, (basenameCount.get(basename) ?? 0) + 1);
  }

  for (const { iconPath, exportName } of iconEntries) {
    const importPath = `@/registry/icons/${iconPath}`;
    const basename = iconPath.split('/').at(-1);

    registryEntries.set(iconPath, { importPath, exportName });

    if (basename && basenameCount.get(basename) === 1) {
      registryEntries.set(basename, { importPath, exportName });
    }
  }

  const lines = [...registryEntries.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([name, entry]) =>
        `  ${JSON.stringify(name)}: ${buildIconLoaderSource(
          entry.importPath,
          entry.exportName,
        )},`,
    );

  return `// This file is autogenerated by scripts/svg-registry.mts
// Do not edit this file directly.

import type { ComponentType } from 'react';
import type { SvgProps } from '@/registry/icons/general/types';

export type IconLoader = () => Promise<{
  default: ComponentType<SvgProps>;
}>;

export const SVG_REGISTRY: Record<string, IconLoader> = {
${lines.join('\n')}
};
`;
}

async function buildIconsRegistry() {
  const iconEntries = await collectIconComponentEntries(ICONS_ROOT_PATH);
  const source = buildIconsRegistrySource(iconEntries);

  await fs.writeFile(ICONS_REGISTRY_PATH, source);
  console.log(
    `Icon registry generated: ${iconEntries.length} icons registered.`,
  );
}

buildIconsRegistry().catch((error) => {
  console.error(error);
  process.exit(1);
});
