export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type IconMode = 'light' | 'dark';

export interface IconProps {
  size?: IconSize;
  mode?: IconMode;
  className?: string;
  /** Accessible label for the icon */
  'aria-label'?: string;
  /** Title element for the icon tooltip */
  title?: string;
  [key: string]: any;
}

export interface SvgProps {
  size: number;
  className?: string;
  title?: string;
  role?: string;
  'aria-label'?: string;
  'aria-hidden'?: boolean;
}

export const sizeMap: Record<IconSize, number> = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
};

export const iconNames = [
  'access-method',
  'adapter-script',
  'aggregate',
  'apache',
  'apache-derby',
  'apache-ignite',
  'apache-phoenix',
  'argument',
  'athena',
  'azure',
  'big-query',
  'binary-data',
  'blue-key',
  'body',
  'cassandra',
  'cassandra-file-type',
  'check-constraint',
  'click-house',
  'cockroach-db',
  'collation',
  'collection',
  'collection-key',
  'collection-type',
  'column',
  'column-blue-key',
  'column-blue-key-dot',
  'column-blue-key-dot-index',
  'column-blue-key-index',
  'column-dot',
  'column-dot-index',
  'column-filter',
  'column-gold-blue-key',
  'column-gold-blue-key-dot',
  'column-gold-blue-key-dot-index',
  'column-gold-blue-key-index',
  'column-gold-key',
  'column-gold-key-dot',
  'column-gold-key-dot-index',
  'column-gold-key-index',
  'column-grey-key',
  'column-index',
  'commit',
  'connector',
  'console-run',
  'console-show-plan',
  'couchbase',
  'data-file',
  'data-schema',
  'data-share',
  'data-structure',
  'data-structure-key',
  'database',
  'database-external',
  'database-link',
  'database-objects-group',
  'databricks',
  'db2',
  'ddl-data-source-overlay',
  'ddl-dbms',
  'default-constraint',
  'denodo',
  'document-db',
  'duck-db',
  'dynamo-db',
  'edit-data',
  'editor-output',
  'elasticsearch',
  'exasol',
  'extension',
  'external-schema',
  'file-format',
  'firebird',
  'foreign-datawrapper',
  'foreign-partion-table',
  'foreign-server',
  'foreign-table',
  'function',
  'function-external',
  'function-run',
  'go-to-table',
  'gold-key',
  'google-cloud-dataproc',
  'google-cloud-spanner',
  'greenplum',
  'grey-key',
  'h2',
  'hana',
  'hash-cluster',
  'hash-table',
  'hash-table-key',
  'hive',
  'hive-file-type',
  'hsqldb',
  'ibm',
  'impala',
  'index',
  'index-cluster',
  'index-fun',
  'index-fun-unique',
  'index-unique',
  'informix',
  'intersystem-cache',
  'json-document',
  'json-document-key',
  'kill-data-source-process',
  'level-auto',
  'level-one-declared',
  'level-one-details',
  'level-one-inherited',
  'level-three-declared',
  'level-three-details',
  'level-three-inherited',
  'level-two-declared',
  'level-two-details',
  'level-two-inherited',
  'list',
  'list-key',
  'locked',
  'macro',
  'manage-data-sources',
  'mariadb',
  'materialized-log',
  'materialized-view',
  'microsoft',
  'mimer-sql',
  'mongo-db',
  'mongo-field',
  'mongo-field-gold-key',
  'mysql',
  'netezza',
  'object-group',
  'object-type-attribute',
  'openedge',
  'operator',
  'operator-class',
  'operator-family',
  'oracle',
  'package',
  'partion',
  'partion-table',
  'pin',
  'pin-hovered',
  'pin-selected',
  'pin-selected-hovered',
  'postgresql',
  'presto',
  'preview-changes',
  'procedure',
  'procedure-group',
  'procedure-run',
  'projection',
  'redis',
  'redis-file-type',
  'redshift',
  'refresh-materialized-view',
  'reset',
  'role',
  'rollback',
  'routine',
  'run-database-script',
  'scheduled-event',
  'schema',
  'scripting-script',
  'scroll-down',
  'scroll-up',
  'sequence',
  'server-objects-group',
  'set',
  'set-key',
  'single-record-view',
  'singlestore',
  'snowflake',
  'sorted-set',
  'sorted-set-key',
  'spark',
  'sql-server',
  'sqldmlstatement',
  'sqlgroup-by-type',
  'sqlite',
  'sqlother-statement',
  'sqlselect-statement',
  'stream',
  'stream-key',
  'string',
  'string-key',
  'submit-db',
  'sun',
  'sybase',
  'synonym',
  't-sqlt',
  'table',
  'table-heatmap',
  'table-mapping',
  'tablespace',
  'tarantool',
  'teradata',
  'text-auto-generate',
  'tibero',
  'tidb',
  'trigger',
  'trino',
  'udfscript',
  'unspecified-cluster',
  'user',
  'user-driver',
  'user-group',
  'user-mapping',
  'ut-plsql',
  'vertica',
  'view-parameters',
  'virtual-column',
  'virtual-folder',
  'virtual-key',
  'virtual-view',
  'warehouse',
  'yugabyte',
] as const;

export type IconName = (typeof iconNames)[number];
