export {
  Breakpoints,
  Build,
  Database,
  Debugger,
  EditorIcons,
  FileTypes,
  General,
  Nodes,
  Plugins,
  Run,
  RunConfigurations,
  Terminal,
  Vcs,
  type BreakpointsProps,
  type BuildProps,
  type DatabaseProps,
  type DebuggerProps,
  type EditorIconsProps,
  type FileTypesProps,
  type GeneralProps,
  type NodesProps,
  type PluginsProps,
  type RunConfigurationsProps,
  type RunProps,
  type TerminalProps,
  type VcsProps,
} from './categories';
export {
  createSpriteIcon,
  Icon,
  spriteSizeMap,
  SVG,
  ThemedIcon,
  normalizeIconPath,
  resolveSpriteHref,
  type IconProps,
  type ResolvedTheme,
  type SpriteIconDefinition,
  type SpriteIconProps,
  type SpriteIconSize,
  type SVGProps,
  type ThemedIconProps,
} from './icon';
