export type IconSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl';
export type IconMode = 'light' | 'dark';

export interface IconProps {
  size?: IconSize;
  mode?: IconMode;
  className?: string;
  /** Accessible label for the icon */
  'aria-label'?: string;
  /** Title element for the icon tooltip */
  title?: string;
  [key: string]: any;
}

export interface SvgProps {
  size: number;
  className?: string;
  title?: string;
  role?: string;
  'aria-label'?: string;
  'aria-hidden'?: boolean;
}

export const sizeMap: Record<IconSize, number> = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
};

export const iconNames = [
  'action-script',
  'acync-api',
  'amper',
  'angular-js',
  'angular-jsmonochrome',
  'any-type',
  'api',
  'archive',
  'aspect-j',
  'assembler-go',
  'bun',
  'chameleon',
  'changed-file',
  'changed-files',
  'coffeescript',
  'conditional-statement',
  'contexts',
  'contexts-modifier',
  'css',
  'cucumber',
  'cython-file',
  'deno',
  'diagram',
  'dictionary',
  'dts',
  'dts-property',
  'dts-sub-node',
  'eclipse',
  'editor-config',
  'ejs',
  'exposed',
  'fast-api',
  'flask',
  'freemaker',
  'haskell',
  'hook',
  'html',
  'http-header',
  'http-requests-run-configuration',
  'i18n',
  'idea-module',
  'idl',
  'ignored',
  'image',
  'java',
  'java-class',
  'java-script',
  'jest',
  'jfr',
  'jinja2',
  'js-config',
  'js-doc-closure',
  'json',
  'json-schema',
  'jsp',
  'jspx',
  'jupyter-notebook',
  'kotlin',
  'less',
  'manifest',
  'markdown',
  'maven',
  'maven-ignored',
  'micronaut',
  'microsoft-windows',
  'modified',
  'next-js',
  'nodejs-test-runner',
  'num-py',
  'open-rewrite',
  'open-tofu',
  'package-json',
  'package-lock',
  'pandas',
  'patch',
  'perl',
  'pnpm',
  'pnpm-lock',
  'polars',
  'prettier',
  'properties',
  'proto-file',
  'proto-message',
  'protobuf',
  'py-torch',
  'python',
  'qml',
  'qrc',
  'qt',
  'quatro',
  'redoc',
  'regexp',
  'rst',
  'sarif',
  'sass',
  'scala',
  'scratch',
  'scratches',
  'scss',
  'shell',
  'source-map',
  'sql',
  'svelte',
  'team-city',
  'tensor-flow',
  'terraform',
  'text',
  'ts-config',
  'ts-doc',
  'ui-form',
  'unknown',
  'vite-js',
  'vitest',
  'vue-js',
  'workspace',
  'wsdl',
  'xhtml',
  'xml',
  'xpath',
  'xsd',
  'xsl',
  'yaml',
  'yarn',
  'yarn-lock',
  'react-icon',
  'react',
] as const;

export type IconName = (typeof iconNames)[number];
