'use client';

import { SvgIconsGallery } from '@/components/docs/icons/svg-icons-gallery';
import { iconCategories } from '@/components/docs/icons/icon-data';

const allGeneralIcons = [
  // General core icons
  ...iconCategories.general.icons,
  // Actions
  'general/actions/addFile',
  'general/actions/groupByModule',
  'general/actions/buildAutoReloadChanges',
  'general/actions/checked',
  'general/actions/deploy',
  'general/actions/diagramDiff',
  'general/actions/diffWithClipboard',
  'general/actions/gift',
  'general/actions/groupByClass',
  'general/actions/groupByFile',
  'general/actions/groupByMethod',
  'general/actions/groupByPackage',
  'general/actions/groupByTestProduction',
  'general/actions/inSelection',
  'general/actions/lightning',
  'general/actions/moveToButton',
  'general/actions/openApi',
  'general/actions/playBack',
  'general/actions/playFirst',
  'general/actions/playForward',
  'general/actions/refreshCaches',
  'general/actions/remoteDev',
  'general/actions/synchronize',
  'general/actions/syncSettings',
  'general/actions/template',
  'general/actions/useInTemplate',
  'general/actions/welcome',
  // AI Assistant
  'general/aiAssistant/aiAssistant',
  'general/aiAssistant/aiAssistantColored',
  'general/aiAssistant/aiAssistantDisabled',
  'general/aiAssistant/attached',
  'general/aiAssistant/dislike',
  'general/aiAssistant/dislikeSelected',
  'general/aiAssistant/featureAnswer',
  'general/aiAssistant/featureCodeBlock',
  'general/aiAssistant/featureComment',
  'general/aiAssistant/featureCommit',
  'general/aiAssistant/featureContext',
  'general/aiAssistant/featureDocs',
  'general/aiAssistant/like',
  'general/aiAssistant/likeSelected',
  'general/aiAssistant/send',
  'general/aiAssistant/sendToEditor',
  'general/aiAssistant/sendToTheLeft',
  'general/aiAssistant/sendToTheLeftGrayed',
  'general/aiAssistant/sendToTheRight',
  'general/aiAssistant/sendToTheRightGrayed',
  // Bookmarks
  'general/bookmarks/bookmarks',
  'general/bookmarks/sendToTheLeft',
  'general/bookmarks/sendToTheLeftGrayed',
  'general/bookmarks/sendToTheRight',
  'general/bookmarks/sendToTheRightGrayed',
  // DevKit
  'general/devkit/addSDK',
  'general/devkit/descriptionFile',
  'general/devkit/diff',
  'general/devkit/plugin',
  'general/devkit/pluginV2',
  'general/devkit/properties',
  'general/devkit/sdkClosed',
  // Duplicates
  'general/duplicates/editor',
  'general/duplicates/inalyQarkus',
  'general/duplicates/inlayMicronaut',
  'general/duplicates/inlaySpring',
  'general/duplicates/inlayWebInspector',
  // Editor
  'general/editor/addRectangularSelection',
  'general/editor/columnSelection',
  'general/editor/contextMenus',
  'general/editor/copyReference',
  'general/editor/diff',
  'general/editor/enter',
  'general/editor/escape',
  'general/editor/mirrorCursor',
  'general/editor/move',
  'general/editor/rectangularSelection',
  'general/editor/selectAll',
  'general/editor/subwordCompletion',
  'general/editor/switch',
  'general/editor/tablet',
  'general/editor/toggle',
  // Inline
  'general/inline/filter',
  'general/inline/filterdups',
  'general/inline/statisticsPanel',
  // Modifiers
  'general/modifiers/accessLocal',
  'general/modifiers/accessPrivate',
  'general/modifiers/accessProtected',
  'general/modifiers/accessPublic',
  // New UI
  'general/newUi/advancedSettings',
  'general/newUi/appearance',
  'general/newUi/behavior',
  'general/newUi/editorTabs',
  'general/newUi/externalAppearance',
  'general/newUi/layout',
  'general/newUi/mainMenu',
  'general/newUi/navigationBar',
  'general/newUi/presentationMode',
  'general/newUi/registry',
  'general/newUi/skin',
  'general/newUi/toolbar',
  'general/newUi/transparency',
  // Object Browser
  'general/objectBrowser/abbreviatePackageNames',
  'general/objectBrowser/compactEmptyPackages',
  'general/objectBrowser/flattenModules',
  'general/objectBrowser/flattenPackages',
  'general/objectBrowser/showLibraryContents',
  'general/objectBrowser/showMembers',
  'general/objectBrowser/sortAlphabetically',
  'general/objectBrowser/sortByType',
  'general/objectBrowser/sortByUsage',
  'general/objectBrowser/sortByVisibility',
  // Progress Bar
  'general/progressBar/finalMark',
  'general/progressBar/junitTestMark',
  'general/progressBar/locked',
  'general/progressBar/processMark',
  'general/progressBar/runnableMark',
  'general/progressBar/shared',
  'general/progressBar/staticMark',
  'general/progressBar/symlink',
  'general/progressBar/tabAlert',
  // Rating
  'general/rating/feedbackRating',
  'general/rating/feedbackRatingFocused',
  'general/rating/feedbackRatingFocusedOn',
  'general/rating/feedbackRatingOn',
  // Setting Sync
  'general/settingSync/Conflict',
  'general/settingSync/LocalChanges',
  'general/settingSync/RemoteChanges',
  'general/settingSync/statusDisabled',
  'general/settingSync/statusEnabled',
  'general/settingSync/status',
  // Spinner
  ...iconCategories.spinner.icons,
  // Status
  'general/status/progress',
  'general/status/successLogin',
  // Tool Windows
  'general/toolWindows/CMakeToolWindow',
  'general/toolWindows/ConcurrencyDiagramToolwindow',
  'general/toolWindows/aiAssistantToolWindow',
  'general/toolWindows/amazonEMR',
  'general/toolWindows/appEngineToolWindow',
  'general/toolWindows/awsGlueToolWindow',
  'general/toolWindows/buildServerProtocol',
  'general/toolWindows/cdiToolWindow',
  'general/toolWindows/cwmAccess',
  'general/toolWindows/cwmUsers',
  'general/toolWindows/dataprocToolWindow',
  'general/toolWindows/donate',
  'general/toolWindows/exceptionAnalyzer',
  'general/toolWindows/feedback',
  'general/toolWindows/gitLabToolWindow',
  // Usages
  'general/usages/showImportStatements',
  'general/usages/showReadAccess',
  'general/usages/showWriteAccess',
  // Windows
  'general/windows/close',
  'general/windows/closeHovered',
  'general/windows/closeTab',
  'general/windows/ideScale',
  'general/windows/maximize',
  'general/windows/maximizeHovered',
  'general/windows/minimize',
  'general/windows/minimizeHovered',
  'general/windows/move',
  'general/windows/restore',
  'general/windows/restoreHovered',
  'general/windows/showNone',
  'general/windows/showOption',
  'general/windows/showOptionsHovered',
  'general/windows/snap',
  // Access Modifiers
  'general/accessModifiers/public',
  'general/accessModifiers/private',
  'general/accessModifiers/protected',
  'general/accessModifiers/package',
  'general/accessModifiers/publicStatic',
  'general/accessModifiers/privateStatic',
  'general/accessModifiers/protectedStatic',
  'general/accessModifiers/packageStatic',
] as const;

export function GeneralAllIconsGallery() {
  return <SvgIconsGallery icons={allGeneralIcons.map((name) => ({ name }))} />;
}
