// Icon data for galleries - derived from registry/icons directory structure
// Format: { category: { label: string, icons: string[] } }

export interface IconCategory {
  label: string;
  icons: readonly string[];
}

export const iconCategories: Record<string, IconCategory> = {
  breakpoints: {
    label: 'Breakpoints',
    icons: [
      'breakpoints/breakpoint',
      'breakpoints/breakpointDependent',
      'breakpoints/breakpointDisabled',
      'breakpoints/breakpointException',
      'breakpoints/breakpointExceptionDisabled',
      'breakpoints/breakpointField',
      'breakpoints/breakpointFieldDependent',
      'breakpoints/breakpointFieldDisabled',
      'breakpoints/breakpointFieldMuted',
      'breakpoints/breakpointFieldMutedDependent',
      'breakpoints/breakpointFieldMutedDisabled',
      'breakpoints/breakpointFieldUnsuspendent',
      'breakpoints/breakpointFieldUnsuspendentDisabled',
      'breakpoints/breakpointFieldUnsuspendentValid',
      'breakpoints/breakpointFieldValid',
      'breakpoints/breakpointInvalid',
      'breakpoints/breakpointLambda',
      'breakpoints/breakpointMethod',
      'breakpoints/breakpointMethodDependent',
      'breakpoints/breakpointMethodDisabled',
      'breakpoints/breakpointMethodMuted',
      'breakpoints/breakpointMethodMutedDependent',
      'breakpoints/breakpointMethodMutedDisabled',
      'breakpoints/breakpointMethodUnsuspendent',
      'breakpoints/breakpointMethodUnsuspendentDisabled',
      'breakpoints/breakpointMethodUnsuspendentValid',
      'breakpoints/breakpointMethodValid',
      'breakpoints/breakpointMuted',
      'breakpoints/breakpointMutedDependent',
      'breakpoints/breakpointMutedDisabled',
      'breakpoints/breakpointObsolete',
      'breakpoints/breakpointUnsuspendent',
      'breakpoints/breakpointUnsuspendentDisabled',
      'breakpoints/breakpointUnsuspendentValid',
      'breakpoints/breakpointValid',
      'breakpoints/multipleBreakpoints',
      'breakpoints/multipleBreakpointsDisabled',
      'breakpoints/multipleBreakpointsMuted',
      'breakpoints/questionBadge',
    ] as const,
  },
  build: {
    label: 'Build',
    icons: [
      'build/build/build',
      'build/build/dependencyAnalyzer',
      'build/build/gradleLoadChanges',
      'build/build/gradleNavigate',
      'build/build/mavenChildrenProjects',
      'build/build/mavenFlex',
      'build/build/mavenLoadChanges',
      'build/build/mavenModule',
      'build/build/mavenParentProjects',
      'build/build/mavenPlugin',
      'build/build/mavenPluginGoal',
      'build/build/mavenProfiles',
      'build/build/mavenProject',
      'build/build/task',
      'build/build/taskGroup',
      'build/build/toggleOfflineMode',
      'build/build/toggleSkipTestsMode',
      'build/build/updateFolders',
    ] as const,
  },
  general: {
    label: 'General',
    icons: [
      'general/general/add',
      'general/general/autoscrollFromSource',
      'general/general/autoscrollToSource',
      'general/general/checkmark',
      'general/general/chevronDown',
      'general/general/chevronDownHovered',
      'general/general/chevronDownLarge',
      'general/general/chevronLeft',
      'general/general/chevronRight',
      'general/general/chevronUp',
      'general/general/chevronUpLarge',
      'general/general/classHierarchy',
      'general/general/close',
      'general/general/closeSmall',
      'general/general/closeSmallHovered',
      'general/general/collapseAll',
      'general/general/configFile',
      'general/general/copy',
      'general/general/cut',
      'general/general/delete',
      'general/general/down',
      'general/general/download',
      'general/general/edit',
      'general/general/exit',
      'general/general/expandAll',
      'general/general/export',
      'general/general/externalLink',
      'general/general/filter',
      'general/general/graphLayout',
      'general/general/groups',
      'general/general/ideVersion',
      'general/general/ignore',
      'general/general/import',
      'general/general/indent',
      'general/general/info',
      'general/general/inspectCode',
      'general/general/launch',
      'general/general/leave',
      'general/general/left',
      'general/general/link',
      'general/general/markup',
      'general/general/maximize',
      'general/general/minimize',
      'general/general/moreHorizontal',
      'general/general/moreVertical',
      'general/general/moveDown',
      'general/general/moveUp',
      'general/general/newWindow',
      'general/general/no',
      'general/general/openInNewWindow',
      'general/general/palette',
      'general/general/paste',
      'general/general/preview',
      'general/general/question',
      'general/general/redo',
      'general/general/refresh',
      'general/general/register',
      'general/general/remove',
      'general/general/renew',
      'general/general/resize',
      'general/general/restart',
      'general/general/restore',
      'general/general/reveal',
      'general/general/revert',
      'general/general/right',
      'general/general/roll',
      'general/general/search',
      'general/general/searchInBrowser',
      'general/general/settings',
      'general/general/showColumns',
      'general/general/showHide',
      'general/general/shrink',
      'general/general/sort',
      'general/general/splitHorizontally',
      'general/general/splitVertically',
      'general/general/stop',
      'general/general/switcher',
      'general/general/sync',
      'general/general/synchronize',
      'general/general/tenPoint',
      'general/general/threePoint',
      'general/general/toolWindowStart',
      'general/general/undo',
      'general/general/unindent',
      'general/general/unite',
      'general/general/up',
      'general/general/upload',
      'general/general/vcs',
      'general/general/warning',
      'general/general/zoom',
      'general/general/zoomIn',
      'general/general/zoomOut',
    ] as const,
  },
  spinner: {
    label: 'Spinner',
    icons: ['general/spinner/loader'] as const,
  },
} as const;

// For icons with subcategories, use format: category/subcategory/iconname
export const generalSubcategories: Record<string, IconCategory> = {
  actions: {
    label: 'Actions',
    icons: [
      'general/actions/addFile',
      'general/actions/groupByModule',
      'general/actions/buildAutoReloadChanges',
      'general/actions/checked',
      'general/actions/deploy',
      'general/actions/diagramDiff',
      'general/actions/diffWithClipboard',
      'general/actions/gift',
      'general/actions/groupByClass',
      'general/actions/groupByFile',
      'general/actions/groupByMethod',
      'general/actions/groupByPackage',
      'general/actions/groupByTestProduction',
      'general/actions/inSelection',
      'general/actions/lightning',
      'general/actions/moveToButton',
      'general/actions/openApi',
      'general/actions/playBack',
      'general/actions/playFirst',
      'general/actions/playForward',
      'general/actions/refreshCaches',
      'general/actions/remoteDev',
      'general/actions/synchronize',
      'general/actions/syncSettings',
      'general/actions/template',
      'general/actions/useInTemplate',
      'general/actions/welcome',
    ] as const,
  },
  editor: {
    label: 'Editor',
    icons: [
      'general/editor/addRectangularSelection',
      'general/editor/columnSelection',
      'general/editor/contextMenus',
      'general/editor/copyReference',
      'general/editor/diff',
      'general/editor/enter',
      'general/editor/escape',
      'general/editor/mirrorCursor',
      'general/editor/move',
      'general/editor/rectangularSelection',
      'general/editor/selectAll',
      'general/editor/subwordCompletion',
      'general/editor/switch',
      'general/editor/tablet',
      'general/editor/toggle',
    ] as const,
  },
} as const;
