import type { FC } from 'react';
import { cn } from '@/lib/utils';
import { type IconProps, type SvgProps, sizeMap } from '../types';

export type TextAutoGenerateProps = IconProps;

const TextAutoGenerateLight: FC<SvgProps> = ({
  size,
  className,
  title,
  role,
  'aria-label': ariaLabel,
  'aria-hidden': ariaHidden,
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    role={role}
    aria-label={ariaLabel}
    aria-hidden={ariaHidden}
  >
    {title ? <title>{title}</title> : null}
    <path
      d="M12.245 9h1.095L16 16h-1.05l-.64-1.78h-2.965L10.75 16H9.675zm1.765 4.385L12.9 10.33l-.115-.43-.11.43-1.05 3.055z"
      fill="#3574F0"
    />
    <path
      d="M10.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 1 0V4c1.215.912 2 2.365 2 4h1a6 6 0 0 0-2.682-5H13.5a.5.5 0 0 0 0-1zM6 10.5a.5.5 0 0 0-1 0V12a5.002 5.002 0 0 1 2.09-8.918.5.5 0 0 0-.18-.983A6.002 6.002 0 0 0 4.682 13H2.5a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5v-3"
      fill="#6C707E"
    />
  </svg>
);

const TextAutoGenerateDark: FC<SvgProps> = ({
  size,
  className,
  title,
  role,
  'aria-label': ariaLabel,
  'aria-hidden': ariaHidden,
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 16 16"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    role={role}
    aria-label={ariaLabel}
    aria-hidden={ariaHidden}
  >
    {title ? <title>{title}</title> : null}
    <path
      d="M12.245 9h1.095L16 16h-1.05l-.64-1.78h-2.965L10.75 16H9.675zm1.765 4.385L12.9 10.33l-.115-.43-.11.43-1.05 3.055z"
      fill="#548AF7"
    />
    <path
      d="M10.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 1 0V4c1.215.912 2 2.365 2 4h1a6 6 0 0 0-2.682-5H13.5a.5.5 0 0 0 0-1zM6 10.5a.5.5 0 0 0-1 0V12a5.002 5.002 0 0 1 2.09-8.918.5.5 0 0 0-.18-.983A6.002 6.002 0 0 0 4.682 13H2.5a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5v-3"
      fill="#CED0D6"
    />
  </svg>
);

export const TextAutoGenerate: FC<TextAutoGenerateProps> = ({
  size = 'md',
  mode = 'light',
  className,
  'aria-label': ariaLabel,
  title,
  ...props
}) => {
  const SvgComponent =
    mode === 'light' ? TextAutoGenerateLight : TextAutoGenerateDark;

  return (
    <SvgComponent
      size={sizeMap[size]}
      className={cn('inline-block flex-shrink-0', className)}
      title={title}
      role={ariaLabel ? 'img' : 'presentation'}
      aria-label={ariaLabel}
      aria-hidden={!ariaLabel}
      {...props}
    />
  );
};
